import { NextResponse } from "next/server";
import { db } from "@/db";
import { products, settings, reviews } from "@/db/schema";
import { eq } from "drizzle-orm";
import { generateSlug } from "@/lib/slug";

const S = (arr: string[]) => JSON.stringify(arr);

const sampleProducts = [
  // ===== SNEAKERS (12) =====
  { name: "Air Max Velocity", description: "Experience unmatched comfort with our premium Air Max Velocity sneakers. Featuring responsive cushioning, breathable mesh upper, and a sleek modern design that transitions effortlessly from gym to street.", price: "189.99", comparePrice: "229.99", category: "sneakers", brand: "SoleVault Originals", sizes: S(["7","8","9","10","11","12"]), colors: S(["Black","White","Red"]), imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80", images: S(["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80"]), stock: 50, featured: true, active: true, rating: "4.8", reviewCount: 124, tags: S(["hot-deal","new-arrival","top-rated"]) },
  { name: "StreetFlex High-Top", description: "Make a statement with the StreetFlex High-Top. Bold design with ankle support, cushioned insole, and premium canvas construction. The go-to choice for streetwear enthusiasts.", price: "129.99", comparePrice: "159.99", category: "sneakers", brand: "SoleVault Street", sizes: S(["7","8","9","10","11","12","13"]), colors: S(["White","Black","Red","Green"]), imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80", images: S(["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80"]), stock: 60, featured: true, active: true, rating: "4.6", reviewCount: 89, tags: S(["on-sale","top-rated"]) },
  { name: "Retro Classic '88", description: "A throwback to the golden era of sneaker culture. The Retro Classic '88 features vintage styling with modern comfort technology. Premium suede and leather construction.", price: "139.99", comparePrice: "169.99", category: "sneakers", brand: "SoleVault Heritage", sizes: S(["7","8","9","10","11"]), colors: S(["Navy","Cream","Forest Green"]), imageUrl: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80", images: S(["https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80"]), stock: 30, featured: false, active: true, rating: "4.7", reviewCount: 67, tags: S(["on-sale","top-rated"]) },
  { name: "Neon Pulse", description: "Light up the night with Neon Pulse sneakers. Reflective accents, neon colorways, and ultra-responsive foam midsole make these the life of any party.", price: "159.99", comparePrice: "199.99", category: "sneakers", brand: "SoleVault Electric", sizes: S(["7","8","9","10","11","12"]), colors: S(["Neon Green","Electric Blue","Hot Pink"]), imageUrl: "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800&q=80", images: S(["https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800&q=80"]), stock: 40, featured: true, active: true, rating: "4.5", reviewCount: 56, tags: S(["new-arrival","limited"]) },
  { name: "Cloud Walker", description: "Walk on clouds. Literally. The Cloud Walker features our proprietary CloudFoam™ technology for the most comfortable walking experience ever created.", price: "174.99", comparePrice: null, category: "sneakers", brand: "SoleVault Premium", sizes: S(["6","7","8","9","10","11","12"]), colors: S(["Cloud White","Sky Blue","Mist Gray"]), imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80", images: S(["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80"]), stock: 45, featured: false, active: true, rating: "4.9", reviewCount: 201, tags: S(["top-rated"]) },
  { name: "Shadow Black Edition", description: "Stealth meets style. The Shadow Black Edition features an all-black monochrome design with matte finishes. Perfect for those who prefer understated elegance.", price: "164.99", comparePrice: "194.99", category: "sneakers", brand: "SoleVault Dark", sizes: S(["8","9","10","11","12"]), colors: S(["Triple Black","Charcoal"]), imageUrl: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80", images: S(["https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80"]), stock: 25, featured: false, active: true, rating: "4.4", reviewCount: 45, tags: S(["on-sale"]) },
  { name: "Canvas Culture", description: "Express yourself with Canvas Culture. These lightweight canvas sneakers come in vibrant patterns and colors, perfect for creative souls who walk their own path.", price: "79.99", comparePrice: "99.99", category: "sneakers", brand: "SoleVault Art", sizes: S(["6","7","8","9","10","11"]), colors: S(["Tie-Dye","Floral","Abstract"]), imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80", images: S(["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80"]), stock: 75, featured: false, active: true, rating: "4.3", reviewCount: 38, tags: S(["hot-deal","on-sale"]) },
  { name: "Velocity Pro X", description: "Engineered for speed. The Velocity Pro X features a carbon fiber plate, responsive ZoomX foam, and aerodynamic design for peak performance.", price: "219.99", comparePrice: "279.99", category: "sneakers", brand: "SoleVault Pro", sizes: S(["7","8","9","10","11","12"]), colors: S(["Volt","Racing Red","Black"]), imageUrl: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80", images: S(["https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80"]), stock: 15, featured: true, active: true, rating: "4.9", reviewCount: 312, tags: S(["hot-deal","limited","top-rated"]) },
  { name: "Minimalist One", description: "Less is more. The Minimalist One strips away everything unnecessary, leaving you with pure, clean design and uncompromising comfort.", price: "119.99", comparePrice: null, category: "sneakers", brand: "SoleVault Essential", sizes: S(["7","8","9","10","11"]), colors: S(["White","Black","Gray"]), imageUrl: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80", images: S(["https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80"]), stock: 55, featured: false, active: true, rating: "4.6", reviewCount: 78, tags: S(["new-arrival"]) },
  { name: "Platform Rise", description: "Elevate your style with Platform Rise. These chunky platform sneakers add height and attitude to any outfit with their bold silhouette and premium materials.", price: "144.99", comparePrice: "179.99", category: "sneakers", brand: "SoleVault Bold", sizes: S(["5","6","7","8","9","10"]), colors: S(["White/Pink","Black/Gold","Beige"]), imageUrl: "https://images.unsplash.com/photo-1584735175315-9d5df23860e6?w=800&q=80", images: S(["https://images.unsplash.com/photo-1584735175315-9d5df23860e6?w=800&q=80"]), stock: 35, featured: false, active: true, rating: "4.2", reviewCount: 42, tags: S(["on-sale","new-arrival"]) },
  { name: "Knit Breeze", description: "Breathability redefined. Knit Breeze features a full flyknit upper with 360-degree ventilation. Your feet stay cool, dry, and comfortable all day.", price: "134.99", comparePrice: null, category: "sneakers", brand: "SoleVault Air", sizes: S(["7","8","9","10","11","12"]), colors: S(["Ocean Blue","Coral","Mint"]), imageUrl: "https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&q=80", images: S(["https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&q=80"]), stock: 42, featured: false, active: true, rating: "4.5", reviewCount: 63, tags: S(["new-arrival"]) },
  { name: "Metro Flex", description: "From subway to boardroom. Metro Flex sneakers blend professional styling with athletic comfort, featuring genuine leather and memory foam insoles.", price: "154.99", comparePrice: "189.99", category: "sneakers", brand: "SoleVault Urban", sizes: S(["7","8","9","10","11","12"]), colors: S(["Tan","Navy","Burgundy"]), imageUrl: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80", images: S(["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80"]), stock: 38, featured: false, active: true, rating: "4.7", reviewCount: 91, tags: S(["on-sale","top-rated"]) },

  // ===== RUNNING (10) =====
  { name: "Urban Runner Pro", description: "Built for the urban explorer. Combines lightweight construction with durable outsole grip. Perfect for daily runs or casual outings with a modern athletic aesthetic.", price: "149.99", comparePrice: "179.99", category: "running", brand: "SoleVault Run", sizes: S(["7","8","9","10","11"]), colors: S(["Blue","Gray","Black"]), imageUrl: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80", images: S(["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80"]), stock: 35, featured: true, active: true, rating: "4.7", reviewCount: 156, tags: S(["hot-deal","top-rated"]) },
  { name: "Marathon Elite", description: "Go the distance with Marathon Elite. Designed for long-distance runners with energy-return technology, lightweight mesh, and arch support engineered for endurance.", price: "199.99", comparePrice: "249.99", category: "running", brand: "SoleVault Performance", sizes: S(["7","8","9","10","11","12"]), colors: S(["Neon Yellow","Black/Red","White/Blue"]), imageUrl: "https://images.unsplash.com/photo-1562183241-b937e95585b6?w=800&q=80", images: S(["https://images.unsplash.com/photo-1562183241-b937e95585b6?w=800&q=80"]), stock: 20, featured: true, active: true, rating: "4.8", reviewCount: 203, tags: S(["hot-deal","limited","top-rated"]) },
  { name: "SpeedStrike", description: "Born to run fast. SpeedStrike features a carbon-plate midsole, ultra-lightweight mesh, and a responsive cushioning system for race-day performance.", price: "234.99", comparePrice: "289.99", category: "running", brand: "SoleVault Racing", sizes: S(["7","8","9","10","11"]), colors: S(["Volt/Black","Red/White","Blue/Silver"]), imageUrl: "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&q=80", images: S(["https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&q=80"]), stock: 12, featured: false, active: true, rating: "4.9", reviewCount: 178, tags: S(["limited","top-rated"]) },
  { name: "Trail Runner GT", description: "From pavement to trail. The GT series handles any surface with confidence. Aggressive lugs, rock plate protection, and waterproof membrane.", price: "179.99", comparePrice: "219.99", category: "running", brand: "SoleVault Trail", sizes: S(["8","9","10","11","12"]), colors: S(["Forest","Gray/Orange","Black"]), imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80", images: S(["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80"]), stock: 28, featured: false, active: true, rating: "4.6", reviewCount: 87, tags: S(["on-sale"]) },
  { name: "EasyRun Daily", description: "Your everyday running companion. EasyRun Daily provides the perfect balance of cushioning and responsiveness for daily training at an accessible price.", price: "99.99", comparePrice: "129.99", category: "running", brand: "SoleVault Active", sizes: S(["6","7","8","9","10","11","12"]), colors: S(["Black","White","Gray/Teal"]), imageUrl: "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&q=80", images: S(["https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&q=80"]), stock: 90, featured: false, active: true, rating: "4.4", reviewCount: 145, tags: S(["hot-deal","on-sale"]) },
  { name: "Night Glow Runner", description: "Be seen after dark. Night Glow Runner features 3M reflective materials across the upper, LED-compatible lace loops, and high-visibility colorways for safe night running.", price: "159.99", comparePrice: null, category: "running", brand: "SoleVault Safety", sizes: S(["7","8","9","10","11"]), colors: S(["Hi-Vis Yellow","Reflective Silver","Neon Orange"]), imageUrl: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80", images: S(["https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80"]), stock: 33, featured: false, active: true, rating: "4.5", reviewCount: 52, tags: S(["new-arrival"]) },
  { name: "Tempo Racer", description: "Set your personal best. Tempo Racer is engineered for tempo runs and intervals with a propulsive forefoot design and snug racing fit.", price: "169.99", comparePrice: "209.99", category: "running", brand: "SoleVault Speed", sizes: S(["7","8","9","10","11"]), colors: S(["Racing Red","Electric Blue","Black/Gold"]), imageUrl: "https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=800&q=80", images: S(["https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=800&q=80"]), stock: 22, featured: false, active: true, rating: "4.7", reviewCount: 68, tags: S(["on-sale","top-rated"]) },
  { name: "Comfort Stride", description: "Maximum cushioning for maximum comfort. Comfort Stride features triple-density foam, a wide toe box, and plush collar padding for long walks and easy runs.", price: "124.99", comparePrice: null, category: "running", brand: "SoleVault Comfort", sizes: S(["6","7","8","9","10","11","12","13"]), colors: S(["White","Black","Navy"]), imageUrl: "https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=800&q=80", images: S(["https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=800&q=80"]), stock: 65, featured: false, active: true, rating: "4.8", reviewCount: 234, tags: S(["top-rated"]) },
  { name: "Flex Motion", description: "Natural movement, enhanced. Flex Motion mimics barefoot running while providing essential protection. Ultra-flexible sole bends with every step.", price: "109.99", comparePrice: "139.99", category: "running", brand: "SoleVault Natural", sizes: S(["7","8","9","10","11"]), colors: S(["Black","White","Olive"]), imageUrl: "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=800&q=80", images: S(["https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=800&q=80"]), stock: 48, featured: false, active: true, rating: "4.3", reviewCount: 41, tags: S(["on-sale"]) },
  { name: "HyperBoost Max", description: "Explosive energy return. HyperBoost Max uses revolutionary Boost foam technology for unmatched responsiveness. Feel the energy with every stride.", price: "209.99", comparePrice: "259.99", category: "running", brand: "SoleVault Max", sizes: S(["7","8","9","10","11","12"]), colors: S(["Core Black","Cloud White","Solar Red"]), imageUrl: "https://images.unsplash.com/photo-1588361861040-ac9b1018f6d5?w=800&q=80", images: S(["https://images.unsplash.com/photo-1588361861040-ac9b1018f6d5?w=800&q=80"]), stock: 18, featured: true, active: true, rating: "4.9", reviewCount: 287, tags: S(["hot-deal","limited","top-rated"]) },

  // ===== FORMAL (8) =====
  { name: "Classic Leather Elite", description: "Timeless elegance meets modern craftsmanship. Handcrafted from premium Italian leather, perfect for business meetings and special occasions.", price: "259.99", comparePrice: null, category: "formal", brand: "SoleVault Premium", sizes: S(["8","9","10","11","12"]), colors: S(["Brown","Black","Tan"]), imageUrl: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=80", images: S(["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=80"]), stock: 20, featured: true, active: true, rating: "4.8", reviewCount: 95, tags: S(["top-rated"]) },
  { name: "Oxford Gentleman", description: "The quintessential gentleman's shoe. Full-grain leather Oxford with Goodyear welt construction ensures longevity and timeless style.", price: "289.99", comparePrice: "349.99", category: "formal", brand: "SoleVault Luxe", sizes: S(["8","9","10","11","12"]), colors: S(["Black Polish","Cognac","Oxblood"]), imageUrl: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&q=80", images: S(["https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&q=80"]), stock: 15, featured: true, active: true, rating: "4.9", reviewCount: 112, tags: S(["on-sale","top-rated","limited"]) },
  { name: "Derby Prestige", description: "Open-laced elegance for the modern professional. Derby Prestige combines comfort with formality, featuring padded insoles and flexible leather.", price: "229.99", comparePrice: null, category: "formal", brand: "SoleVault Executive", sizes: S(["8","9","10","11"]), colors: S(["Black","Dark Brown"]), imageUrl: "https://images.unsplash.com/photo-1449505278894-297fdb3edbc1?w=800&q=80", images: S(["https://images.unsplash.com/photo-1449505278894-297fdb3edbc1?w=800&q=80"]), stock: 18, featured: false, active: true, rating: "4.6", reviewCount: 54, tags: S(["new-arrival"]) },
  { name: "Loafer Luxe", description: "Effortless sophistication. Slip into the Loafer Luxe with hand-stitched penny loafer detailing and butter-soft calfskin leather.", price: "199.99", comparePrice: "239.99", category: "formal", brand: "SoleVault Luxe", sizes: S(["8","9","10","11","12"]), colors: S(["Burgundy","Navy","Camel"]), imageUrl: "https://images.unsplash.com/photo-1582897085656-c636d006a246?w=800&q=80", images: S(["https://images.unsplash.com/photo-1582897085656-c636d006a246?w=800&q=80"]), stock: 22, featured: false, active: true, rating: "4.5", reviewCount: 73, tags: S(["on-sale"]) },
  { name: "Monk Strap Master", description: "Double monk strap design for the fashion-forward professional. Premium buckle hardware and hand-burnished leather finish.", price: "274.99", comparePrice: null, category: "formal", brand: "SoleVault Artisan", sizes: S(["8","9","10","11"]), colors: S(["Mahogany","Black"]), imageUrl: "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=800&q=80", images: S(["https://images.unsplash.com/photo-1560343090-f0409e92791a?w=800&q=80"]), stock: 12, featured: false, active: true, rating: "4.7", reviewCount: 38, tags: S(["limited"]) },
  { name: "Patent Gala", description: "Ready for the red carpet. Patent Gala features mirror-finish patent leather with a sleek pointed toe. The ultimate formal evening shoe.", price: "319.99", comparePrice: "399.99", category: "formal", brand: "SoleVault Couture", sizes: S(["8","9","10","11","12"]), colors: S(["Black Patent","Midnight Blue"]), imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80", images: S(["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80"]), stock: 8, featured: false, active: true, rating: "4.8", reviewCount: 29, tags: S(["hot-deal","limited"]) },
  { name: "Brogue Heritage", description: "Classic broguing meets contemporary comfort. Full-brogue wingtip design with cushioned footbed and flexible Dainite sole.", price: "244.99", comparePrice: "294.99", category: "formal", brand: "SoleVault Heritage", sizes: S(["8","9","10","11","12"]), colors: S(["Walnut","Black","Tan"]), imageUrl: "https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?w=800&q=80", images: S(["https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?w=800&q=80"]), stock: 16, featured: false, active: true, rating: "4.6", reviewCount: 61, tags: S(["on-sale"]) },
  { name: "Chelsea Formal", description: "Where casual meets formal. The Chelsea Formal boot features elastic side panels, pull tabs, and polished leather for versatile styling.", price: "234.99", comparePrice: null, category: "formal", brand: "SoleVault Modern", sizes: S(["8","9","10","11"]), colors: S(["Black","Espresso","Sand"]), imageUrl: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=800&q=80", images: S(["https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=800&q=80"]), stock: 20, featured: false, active: true, rating: "4.4", reviewCount: 47, tags: S(["new-arrival"]) },

  // ===== BOOTS (10) =====
  { name: "Trail Blazer X", description: "Conquer any terrain. Waterproof construction, aggressive tread pattern, and reinforced toe cap make these the ultimate hiking companion.", price: "199.99", comparePrice: "249.99", category: "boots", brand: "SoleVault Outdoor", sizes: S(["8","9","10","11","12"]), colors: S(["Brown","Dark Green","Black"]), imageUrl: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80", images: S(["https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80"]), stock: 25, featured: true, active: true, rating: "4.7", reviewCount: 143, tags: S(["hot-deal","top-rated"]) },
  { name: "Arctic Commander", description: "Brave the cold with Arctic Commander. Insulated with Thinsulate, waterproof leather, and aggressive winter traction for sub-zero conditions.", price: "249.99", comparePrice: "309.99", category: "boots", brand: "SoleVault Winter", sizes: S(["8","9","10","11","12"]), colors: S(["Black","Brown","Olive"]), imageUrl: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80", images: S(["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80"]), stock: 18, featured: false, active: true, rating: "4.8", reviewCount: 98, tags: S(["hot-deal","limited"]) },
  { name: "Urban Chelsea", description: "City-ready Chelsea boots with elastic panels and pull-tab. Premium suede construction with stacked leather heel.", price: "179.99", comparePrice: null, category: "boots", brand: "SoleVault City", sizes: S(["7","8","9","10","11","12"]), colors: S(["Tan","Black","Gray"]), imageUrl: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&q=80", images: S(["https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&q=80"]), stock: 32, featured: false, active: true, rating: "4.5", reviewCount: 76, tags: S(["new-arrival"]) },
  { name: "Moto Rebel", description: "Rebel spirit, refined design. Moto Rebel features heavy-duty hardware, oil-resistant sole, and vintage-distressed leather for that lived-in look.", price: "219.99", comparePrice: "269.99", category: "boots", brand: "SoleVault Moto", sizes: S(["8","9","10","11","12"]), colors: S(["Distressed Brown","Aged Black"]), imageUrl: "https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=800&q=80", images: S(["https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=800&q=80"]), stock: 14, featured: false, active: true, rating: "4.6", reviewCount: 55, tags: S(["on-sale","limited"]) },
  { name: "Lumberjack Pro", description: "Built for work, designed for style. The Lumberjack Pro features steel toe protection, waterproof leather, and anti-fatigue insole technology.", price: "189.99", comparePrice: "229.99", category: "boots", brand: "SoleVault Work", sizes: S(["8","9","10","11","12","13"]), colors: S(["Wheat","Dark Brown","Black"]), imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80", images: S(["https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80"]), stock: 40, featured: false, active: true, rating: "4.7", reviewCount: 167, tags: S(["on-sale","top-rated"]) },
  { name: "Desert Storm", description: "Inspired by military heritage. Desert Storm boots feature breathable suede, crepe rubber sole, and classic two-eyelet design.", price: "149.99", comparePrice: null, category: "boots", brand: "SoleVault Military", sizes: S(["7","8","9","10","11","12"]), colors: S(["Sand","Olive","Dark Earth"]), imageUrl: "https://images.unsplash.com/photo-1614252234498-1b460c14e23a?w=800&q=80", images: S(["https://images.unsplash.com/photo-1614252234498-1b460c14e23a?w=800&q=80"]), stock: 28, featured: false, active: true, rating: "4.4", reviewCount: 82, tags: S(["new-arrival"]) },
  { name: "Summit Peak", description: "Reach new heights. Summit Peak mountaineering boots feature Vibram soles, crampon-compatible design, and Gore-Tex waterproof lining.", price: "299.99", comparePrice: "369.99", category: "boots", brand: "SoleVault Alpine", sizes: S(["8","9","10","11","12"]), colors: S(["Gray/Blue","Black/Orange"]), imageUrl: "https://images.unsplash.com/photo-1606890658317-7d14490b76fd?w=800&q=80", images: S(["https://images.unsplash.com/photo-1606890658317-7d14490b76fd?w=800&q=80"]), stock: 10, featured: false, active: true, rating: "4.9", reviewCount: 45, tags: S(["hot-deal","limited","top-rated"]) },
  { name: "Rain Guardian", description: "Stay dry in style. Rain Guardian features fully waterproof rubber construction with a neoprene lining for warmth and a non-slip outsole.", price: "89.99", comparePrice: "119.99", category: "boots", brand: "SoleVault Weather", sizes: S(["6","7","8","9","10","11","12"]), colors: S(["Hunter Green","Navy","Black","Red"]), imageUrl: "https://images.unsplash.com/photo-1610398752800-146f269dfcc8?w=800&q=80", images: S(["https://images.unsplash.com/photo-1610398752800-146f269dfcc8?w=800&q=80"]), stock: 55, featured: false, active: true, rating: "4.3", reviewCount: 121, tags: S(["hot-deal","on-sale"]) },
  { name: "Vintage Hiker", description: "Old-school hiking aesthetics with modern trail technology. Vintage Hiker features retro colorways, suede panels, and EVA midsole cushioning.", price: "164.99", comparePrice: null, category: "boots", brand: "SoleVault Retro", sizes: S(["7","8","9","10","11"]), colors: S(["Rust/Green","Navy/Tan","Gray/Yellow"]), imageUrl: "https://images.unsplash.com/photo-1605733513597-a8f8341084e6?w=800&q=80", images: S(["https://images.unsplash.com/photo-1605733513597-a8f8341084e6?w=800&q=80"]), stock: 24, featured: false, active: true, rating: "4.5", reviewCount: 37, tags: S(["new-arrival"]) },
  { name: "Tactical Force", description: "Mission-ready tactical boots. Tactical Force features side-zip entry, anti-microbial lining, and oil/slip-resistant outsoles built for demanding environments.", price: "214.99", comparePrice: "264.99", category: "boots", brand: "SoleVault Tactical", sizes: S(["8","9","10","11","12","13"]), colors: S(["Coyote","Black","Sage"]), imageUrl: "https://images.unsplash.com/photo-1626947346165-4c2288dadc2a?w=800&q=80", images: S(["https://images.unsplash.com/photo-1626947346165-4c2288dadc2a?w=800&q=80"]), stock: 19, featured: false, active: true, rating: "4.6", reviewCount: 89, tags: S(["on-sale"]) },

  // ===== SANDALS (5) =====
  { name: "Slide Comfort Plus", description: "Ultimate relaxation for your feet. Memory foam insole and ergonomic design for maximum comfort during casual wear.", price: "59.99", comparePrice: "79.99", category: "sandals", brand: "SoleVault Comfort", sizes: S(["7","8","9","10","11"]), colors: S(["Black","Navy","Gray"]), imageUrl: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80", images: S(["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80"]), stock: 80, featured: false, active: true, rating: "4.4", reviewCount: 198, tags: S(["hot-deal","on-sale"]) },
  { name: "Beach Voyager", description: "Ready for sand and surf. Beach Voyager features quick-dry straps, contoured footbed, and water-friendly construction.", price: "49.99", comparePrice: "69.99", category: "sandals", brand: "SoleVault Beach", sizes: S(["6","7","8","9","10","11","12"]), colors: S(["Blue","Green","Black","Orange"]), imageUrl: "https://images.unsplash.com/photo-1562273138-f46be7c22640?w=800&q=80", images: S(["https://images.unsplash.com/photo-1562273138-f46be7c22640?w=800&q=80"]), stock: 95, featured: false, active: true, rating: "4.2", reviewCount: 156, tags: S(["hot-deal","on-sale"]) },
  { name: "Sport Slide Elite", description: "Recovery reimagined. Sport Slide Elite features massage-point footbed and cushioned arch support. Perfect after intense workouts.", price: "69.99", comparePrice: null, category: "sandals", brand: "SoleVault Sport", sizes: S(["7","8","9","10","11","12"]), colors: S(["Black/White","Navy/Gold","All Black"]), imageUrl: "https://images.unsplash.com/photo-1608667508764-33cf0726b13a?w=800&q=80", images: S(["https://images.unsplash.com/photo-1608667508764-33cf0726b13a?w=800&q=80"]), stock: 60, featured: false, active: true, rating: "4.5", reviewCount: 87, tags: S(["new-arrival"]) },
  { name: "Leather Crafted Sandal", description: "Artisan-crafted leather sandals with hand-stitched detailing. Premium vegetable-tanned leather develops a beautiful patina over time.", price: "119.99", comparePrice: "149.99", category: "sandals", brand: "SoleVault Artisan", sizes: S(["7","8","9","10","11"]), colors: S(["Natural Tan","Dark Brown","Black"]), imageUrl: "https://images.unsplash.com/photo-1617812754202-5cc59bdda0e5?w=800&q=80", images: S(["https://images.unsplash.com/photo-1617812754202-5cc59bdda0e5?w=800&q=80"]), stock: 25, featured: false, active: true, rating: "4.7", reviewCount: 43, tags: S(["on-sale","top-rated"]) },
  { name: "Adventure Trekker", description: "Sandals built for the trail. Adjustable straps, toe protection, and rugged outsole grip for light hiking and outdoor adventures.", price: "84.99", comparePrice: "109.99", category: "sandals", brand: "SoleVault Trek", sizes: S(["7","8","9","10","11","12"]), colors: S(["Olive/Black","Brown/Tan","Gray/Blue"]), imageUrl: "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=800&q=80", images: S(["https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=800&q=80"]), stock: 35, featured: false, active: true, rating: "4.3", reviewCount: 65, tags: S(["on-sale","new-arrival"]) },

  // ===== CASUAL (5) =====
  { name: "Weekend Slip-On", description: "Weekend ready. Slide into the Weekend Slip-On for effortless style. Soft canvas upper and cushioned insole for all-day comfort.", price: "74.99", comparePrice: "94.99", category: "casual", brand: "SoleVault Weekend", sizes: S(["7","8","9","10","11","12"]), colors: S(["Navy","Khaki","White","Black"]), imageUrl: "https://images.unsplash.com/photo-1604671368394-2240d0b1bb6c?w=800&q=80", images: S(["https://images.unsplash.com/photo-1604671368394-2240d0b1bb6c?w=800&q=80"]), stock: 70, featured: false, active: true, rating: "4.5", reviewCount: 112, tags: S(["hot-deal","on-sale"]) },
  { name: "Coastal Deck", description: "Nautical inspiration meets everyday style. Coastal Deck features hand-sewn moccasin construction and non-marking rubber outsole.", price: "94.99", comparePrice: null, category: "casual", brand: "SoleVault Maritime", sizes: S(["7","8","9","10","11"]), colors: S(["Boat Brown","Navy","Bone"]), imageUrl: "https://images.unsplash.com/photo-1614252370475-0a39afe92aab?w=800&q=80", images: S(["https://images.unsplash.com/photo-1614252370475-0a39afe92aab?w=800&q=80"]), stock: 40, featured: false, active: true, rating: "4.6", reviewCount: 78, tags: S(["new-arrival","top-rated"]) },
  { name: "Espadrille Summer", description: "Summer vibes only. The Espadrille Summer features a woven jute sole, canvas upper, and slip-on design for breezy warm-weather style.", price: "64.99", comparePrice: "84.99", category: "casual", brand: "SoleVault Summer", sizes: S(["6","7","8","9","10","11"]), colors: S(["Natural","Blue Stripe","Red"]), imageUrl: "https://images.unsplash.com/photo-1573100925118-870b8efc799d?w=800&q=80", images: S(["https://images.unsplash.com/photo-1573100925118-870b8efc799d?w=800&q=80"]), stock: 55, featured: false, active: true, rating: "4.2", reviewCount: 34, tags: S(["on-sale"]) },
  { name: "Suede Chukka", description: "Versatile and refined. The Suede Chukka transitions seamlessly from smart casual to weekend wear with premium suede and clean lines.", price: "159.99", comparePrice: "189.99", category: "casual", brand: "SoleVault Style", sizes: S(["8","9","10","11","12"]), colors: S(["Desert","Charcoal","Forest"]), imageUrl: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80", images: S(["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80"]), stock: 30, featured: false, active: true, rating: "4.7", reviewCount: 91, tags: S(["on-sale","top-rated"]) },
  { name: "Driving Moc", description: "Luxury driving shoes with rubber pebble outsole and soft unlined interior. Italian-inspired design for the discerning driver.", price: "139.99", comparePrice: null, category: "casual", brand: "SoleVault Drive", sizes: S(["8","9","10","11","12"]), colors: S(["Italian Red","Midnight","Tobacco"]), imageUrl: "https://images.unsplash.com/photo-1612011213372-4b9a04845eea?w=800&q=80", images: S(["https://images.unsplash.com/photo-1612011213372-4b9a04845eea?w=800&q=80"]), stock: 20, featured: false, active: true, rating: "4.8", reviewCount: 56, tags: S(["new-arrival","top-rated"]) },
];

// Reviews mapped to specific product indices
// Index 0-11: sneakers, 12-21: running, 22-29: formal, 30-39: boots, 40-44: sandals, 45-49: casual
const productReviewsMap: Record<number, Array<{ customerName: string; rating: number; comment: string; avatar: string; verified: boolean }>> = {
  // Air Max Velocity (index 0)
  0: [
    { customerName: "James Wilson", rating: 5, comment: "I've been wearing sneakers for 20 years and these are hands down the most comfortable pair I've ever owned. The cushioning feels like walking on clouds, and the mesh upper keeps my feet cool even during summer. The red colorway is absolutely stunning — I get compliments every time I wear them. Worth every penny.", avatar: "JW", verified: true },
    { customerName: "Priya Sharma", rating: 5, comment: "Bought these for my husband's birthday and he hasn't taken them off since! The quality of the materials is immediately obvious when you hold them. The stitching is perfect, the sole has great grip, and they look even better in person than in the photos. Already planning to buy the black pair too.", avatar: "PS", verified: true },
    { customerName: "Marcus Johnson", rating: 4, comment: "Really solid sneakers. The comfort level is 10/10 right out of the box — no break-in period needed. Only giving 4 stars because the sizing runs slightly large. I'm usually a 10 but had to exchange for a 9.5. Other than that, these are perfect. The design is clean and modern.", avatar: "MJ", verified: true },
    { customerName: "Sophie Laurent", rating: 5, comment: "These sneakers are incredible! I walk about 5 miles a day for work and my feet used to ache by the afternoon. Since switching to the Air Max Velocity, zero pain. The arch support is phenomenal. Also, they look super stylish — I've gotten stopped on the street by people asking where I got them!", avatar: "SL", verified: true },
  ],
  // StreetFlex High-Top (index 1)
  1: [
    { customerName: "Tyler Brooks", rating: 5, comment: "The StreetFlex High-Tops are fire! I'm a huge sneakerhead and these instantly became my #1 rotation shoe. The ankle support is legit — I can skateboard in them comfortably. The canvas quality is thick and durable, not flimsy like some other brands. Already have two pairs.", avatar: "TB", verified: true },
    { customerName: "Rachel Kim", rating: 4, comment: "Love the retro high-top look! These pair perfectly with cropped jeans and a leather jacket. The cushioned insole is surprisingly comfortable for a canvas shoe. Took one star off because the white ones do scuff easily, but a magic eraser takes care of that. Overall a great buy.", avatar: "RK", verified: true },
    { customerName: "Derek Williams", rating: 5, comment: "Best high-tops I've owned. Period. The build quality reminds me of the classic Chuck Taylors but with way better comfort and support. I've worn them to concerts, skateparks, and even hiking — they handle everything. The green colorway is unique and always gets noticed.", avatar: "DW", verified: true },
  ],
  // Neon Pulse (index 3)
  3: [
    { customerName: "Jade Martinez", rating: 5, comment: "OH MY GOD these shoes are AMAZING! The neon green colorway literally glows under blacklights — I wore them to a club and everyone was freaking out. But they're not just flashy — the foam midsole is incredibly responsive and comfortable. I danced for 4 hours straight with zero foot pain.", avatar: "JM", verified: true },
    { customerName: "Ryan O'Connor", rating: 4, comment: "Really fun shoes with great comfort. The reflective accents are a nice touch for night walks. Only minor complaint is that the electric blue color is slightly different from the website photos — a bit more purple in person. Still love them though, just wish the color was more accurate.", avatar: "RO", verified: true },
  ],
  // Cloud Walker (index 4)
  4: [
    { customerName: "Emma Thompson", rating: 5, comment: "I have plantar fasciitis and finding comfortable shoes has been a nightmare for years. My podiatrist recommended shoes with good arch support, and the Cloud Walkers exceeded every expectation. I can stand for 8-hour shifts at work without any pain. These literally changed my life. Thank you SoleVault!", avatar: "ET", verified: true },
    { customerName: "Carlos Rivera", rating: 5, comment: "The name doesn't lie — you really do feel like you're walking on clouds. I'm a mail carrier and walk 12+ miles daily. These are the only shoes that don't leave my feet hurting at the end of the day. The white colorway stays clean easily too. Buying a backup pair just in case.", avatar: "CR", verified: true },
    { customerName: "Nina Patel", rating: 5, comment: "I'm on my third pair of Cloud Walkers because they're just that good. The CloudFoam technology is something special — it molds to your foot shape over time. My first pair lasted 18 months of daily use before the tread wore down. That's incredible durability for the price.", avatar: "NP", verified: true },
  ],
  // Velocity Pro X (index 7)
  7: [
    { customerName: "Alex Chen", rating: 5, comment: "As a competitive marathon runner, I'm very picky about my race shoes. The Velocity Pro X blew me away — the carbon fiber plate gives incredible propulsion and I knocked 3 minutes off my PR in my first race wearing them. The lightweight mesh barely feels like you're wearing shoes. Elite performance.", avatar: "AC", verified: true },
    { customerName: "Jordan Bell", rating: 5, comment: "These are THE running shoes to beat right now. The ZoomX-style foam is incredibly bouncy and responsive. I've run 200+ miles in them and they still feel fresh. The racing red colorway looks fast just sitting on the shelf. If you're serious about running, buy these immediately.", avatar: "JB", verified: true },
    { customerName: "Maria Santos", rating: 4, comment: "Amazing performance shoes. The carbon plate really does make you feel faster — there's a noticeable 'snap' with each stride. Only giving 4 stars because the fit is very narrow around the midfoot. If you have wide feet, go up half a size. Otherwise, these are perfect racing shoes.", avatar: "MS", verified: true },
  ],
  // Urban Runner Pro (index 12)
  12: [
    { customerName: "Brian Foster", rating: 5, comment: "Perfect daily trainers. I run 30-40 miles per week and these hold up beautifully. The outsole grip is phenomenal — I've run in rain, on gravel, and on trails without any slipping. The breathable upper keeps my feet dry and comfortable. Can't ask for more at this price point.", avatar: "BF", verified: true },
    { customerName: "Sarah Chen", rating: 5, comment: "I bought these as my first 'real' running shoes and I'm so glad I did. The difference between these and my old sneakers is night and day. The cushioning absorbs impact perfectly, my knees don't hurt anymore after runs, and they look sleek enough to wear casually. Best investment I've made in my fitness.", avatar: "SC", verified: true },
  ],
  // Marathon Elite (index 13)
  13: [
    { customerName: "Kevin Nguyen", rating: 5, comment: "Trained for and ran my first full marathon in these shoes. 26.2 miles and my feet felt great the entire time. The energy return technology is real — you can literally feel the bounce propelling you forward in the later miles when you're most fatigued. Finished in 3:28, couldn't be happier!", avatar: "KN", verified: true },
    { customerName: "Diana Ross", rating: 5, comment: "I'm a running coach and I recommend the Marathon Elite to all my athletes training for long distances. The cushioning-to-weight ratio is best in class. They're incredibly lightweight but still provide enough protection for 20+ mile runs. The neon yellow colorway is also great for visibility.", avatar: "DR", verified: true },
    { customerName: "Tom Bradley", rating: 4, comment: "Excellent long-distance shoes. I've completed three half marathons in them and they've been rock solid. The arch support is perfect for my flat feet. My only wish is that they came in more color options — I had to go with black/red which is fine but I wanted something more unique.", avatar: "TB", verified: true },
  ],
  // Classic Leather Elite (index 22)
  22: [
    { customerName: "Amanda Blake", rating: 5, comment: "These are the most beautiful formal shoes I've ever owned. The Italian leather has this incredible richness and depth of color that you can only get from premium materials. I wore them to a wedding and received more compliments on my shoes than the bride got on her dress! The comfort is remarkable too — no blisters, no pinching.", avatar: "AB", verified: true },
    { customerName: "William Harris", rating: 5, comment: "I work in finance and need shoes that look professional day after day. These Leather Elites are exceptional — the craftsmanship is evident in every detail. The hand-stitched welt, the leather sole, the perfectly shaped last. After 6 months of near-daily wear, they've developed a gorgeous patina. These are investment shoes.", avatar: "WH", verified: true },
    { customerName: "Michael Torres", rating: 5, comment: "Bought the brown pair for work and was so impressed I came back for black. The quality rivals shoes I've seen at twice the price from luxury brands. The leather is soft and supple right out of the box — no painful break-in period. My go-to for client meetings and formal events.", avatar: "MT", verified: true },
  ],
  // Oxford Gentleman (index 23)
  23: [
    { customerName: "Christopher Lee", rating: 5, comment: "The Goodyear welt construction on these Oxfords is the real deal. You can feel the quality difference compared to glued shoes immediately. The full-grain leather creaks satisfyingly when new and develops character over time. I've had mine resoled once and they look better than ever. These are shoes for life.", avatar: "CL", verified: true },
    { customerName: "Robert Chen", rating: 5, comment: "I paid $300 for these and they make my $500 Allen Edmonds look overpriced. The cognac color is rich and warm, the shape is elegant without being too pointy, and the comfort is superb for a formal shoe. The Dainite sole provides good grip on wet surfaces. Simply outstanding.", avatar: "RC", verified: true },
  ],
  // Trail Blazer X (index 30)
  30: [
    { customerName: "Jake Morrison", rating: 5, comment: "Took these on a 5-day hiking trip through the Appalachian Trail and they were absolutely phenomenal. Waterproof kept my feet bone dry through stream crossings and rain, the tread gripped slippery rocks like glue, and the reinforced toe saved me from painful stub on at least three occasions. Essential hiking gear.", avatar: "JM", verified: true },
    { customerName: "Lisa Anderson", rating: 4, comment: "Great hiking boots overall. Very sturdy and well-constructed. The waterproofing works perfectly — I tested them in ankle-deep puddles and stayed dry. The only reason for 4 stars is they're a bit heavy compared to trail runners, which slows you down on longer hikes. But for rugged terrain, you want this level of protection.", avatar: "LA", verified: true },
    { customerName: "Daniel Park", rating: 5, comment: "I work as a park ranger and need boots I can rely on every single day. The Trail Blazer X has been my go-to for the past year. Through mud, snow, rain, and rocky terrain — these boots handle it all. The ankle support is excellent and prevents rolling on uneven ground. Already on my second pair.", avatar: "DP", verified: true },
  ],
  // Arctic Commander (index 31)
  31: [
    { customerName: "Erik Johansson", rating: 5, comment: "I live in Minnesota where winters hit -30°F regularly. These Arctic Commander boots kept my feet warm and dry through the entire season. The Thinsulate insulation is incredibly effective, and the waterproof leather has withstood salt, slush, and deep snow. The aggressive tread also prevented me from slipping on ice. Best winter boots I've ever owned.", avatar: "EJ", verified: true },
    { customerName: "Maria Volkov", rating: 5, comment: "Bought these for a trip to Iceland in January. Walked on glaciers, through snowstorms, and across frozen rivers. My feet were warm and completely dry the entire time. They're also surprisingly comfortable for heavy boots — no break-in blisters. Absolutely essential for cold climate adventures.", avatar: "MV", verified: true },
  ],
  // Slide Comfort Plus (index 40)
  40: [
    { customerName: "David Kim", rating: 5, comment: "These slides are my house shoes now. The memory foam insole is so plush and comfortable — I literally sigh with relief every time I slip them on after a long day. I've bought pairs for my whole family because they're that good. The navy color looks great and hasn't faded after months of use.", avatar: "DK", verified: true },
    { customerName: "Jenny Liu", rating: 4, comment: "Super comfortable slides for the price. The cushioning is better than some slides that cost three times as much. They're perfect for running errands, walking the dog, or just lounging around the house. I knocked one star because the sizing is a bit off — I'd recommend going one size up from your usual.", avatar: "JL", verified: true },
  ],
  // Weekend Slip-On (index 45)
  45: [
    { customerName: "Patrick O'Brien", rating: 5, comment: "These slip-ons have become my daily drivers. I throw them on for everything — grocery shopping, walking the dog, casual dinners, weekend trips. The canvas is durable and easy to clean, and the cushioned insole makes them comfortable enough for all-day wear. I have them in three colors now!", avatar: "PO", verified: true },
    { customerName: "Amy Zhang", rating: 5, comment: "The perfect lazy weekend shoe! So easy to just slide on and go. They look much more expensive than they are — I've gotten compliments from people who assumed they were designer shoes. The khaki color goes with everything. My only regret is not buying these sooner.", avatar: "AZ", verified: true },
    { customerName: "Steve Robinson", rating: 4, comment: "Nice casual shoes that punch above their weight in terms of quality. The stitching is tight, the canvas is thick, and they feel solid on your feet. My only nitpick is I wish they had a bit more arch support for long walking days. But for casual everyday wear, these are excellent.", avatar: "SR", verified: true },
  ],
  // Suede Chukka (index 48)
  48: [
    { customerName: "Oliver Grant", rating: 5, comment: "The Suede Chukka has replaced all my other casual boots. The desert colorway is gorgeous and matches literally everything in my wardrobe. The suede quality is incredible — it has a beautiful nap and texture that makes these look way more expensive than $160. I wear them to the office and on dates alike.", avatar: "OG", verified: true },
    { customerName: "Hannah Mitchell", rating: 5, comment: "Bought these for my boyfriend and he LOVES them. He says they're the most comfortable boots he's ever worn. The suede is soft and the crepe sole has great flexibility. They've held up beautifully through fall and winter too — no damage from light rain. Highly recommend!", avatar: "HM", verified: true },
  ],
  // Driving Moc (index 49)
  49: [
    { customerName: "Antonio Rossi", rating: 5, comment: "As an Italian car enthusiast, I take my driving shoes seriously. These Driving Mocs are exceptional — the pebbled rubber sole gives perfect pedal feel, and the unlined leather interior is buttery soft. The tobacco color develops a beautiful patina with wear. These are a daily pleasure to put on.", avatar: "AR", verified: true },
    { customerName: "Grace Chen", rating: 5, comment: "Gifted these to my father for his birthday and he was overjoyed. The Italian-inspired design is elegant and the quality of leather is outstanding. He wears them not just for driving but for everything casual now. The midnight color is sleek and sophisticated. Already bought a pair for my husband too!", avatar: "GC", verified: true },
  ],
  // HyperBoost Max (index 21)
  21: [
    { customerName: "Liam Donovan", rating: 5, comment: "The Boost foam in these is next level. I've run in a lot of shoes with energy-return foam but the HyperBoost Max is in its own league. Every step feels like a mini trampoline pushing you forward. I ran a 10K PR by over a minute on my first race in them. The core black colorway is clean and goes with everything.", avatar: "LD", verified: true },
    { customerName: "Naomi Wallace", rating: 5, comment: "I've been running for 15 years and these might be the best overall running shoes I've ever worn. The cushioning is perfect — enough to protect on long runs but responsive enough for speed work. I use them for everything from easy recovery jogs to tempo runs and they excel at all of it.", avatar: "NW", verified: true },
  ],
  // Rain Guardian (index 37)
  37: [
    { customerName: "Emily Parker", rating: 4, comment: "Finally! Rain boots that don't look like rain boots. The Hunter Green color is stylish enough to wear to brunch, but they're fully waterproof for trudging through puddles on my commute. The neoprene lining keeps my feet warm and the non-slip sole has saved me from wiping out on wet sidewalks multiple times.", avatar: "EP", verified: true },
    { customerName: "Jason Wright", rating: 5, comment: "Best value rain boots on the market. I've tried expensive brands like Hunter and Aigle, but these SoleVault Rain Guardians are just as waterproof and more comfortable thanks to the neoprene lining. Plus they're a fraction of the price. The black color looks great and goes with everything.", avatar: "JW", verified: true },
    { customerName: "Katie Sullivan", rating: 4, comment: "Love these for rainy spring days! They keep my feet completely dry and the sole has great grip. The red color is super cute and always gets compliments. Only giving 4 stars because they can get a bit warm in temperatures above 60°F since they're fully rubber. But for their intended purpose, they're perfect.", avatar: "KS", verified: true },
  ],
  // Lumberjack Pro (index 34)
  34: [
    { customerName: "Mike Thompson", rating: 5, comment: "I work construction and these boots are the real deal. The steel toe has saved my feet at least twice from falling tools. The waterproof leather keeps me dry even working in the rain, and the anti-fatigue insole is a game changer for 12-hour shifts. These are workhorses that also look good enough for a casual dinner.", avatar: "MT", verified: true },
    { customerName: "Chris Walker", rating: 5, comment: "After going through a pair of work boots every 6 months, I invested in the Lumberjack Pro and they've lasted over a year of hard daily use. The quality difference is immediately noticeable — the leather is thick and resilient, the sole barely shows wear. The wheat color looks great and hides dirt well.", avatar: "CW", verified: true },
  ],
};

export async function POST() {
  try {
    // Initialize settings
    const existingSettings = await db.select().from(settings).where(eq(settings.id, 1));
    if (existingSettings.length === 0) {
      await db.insert(settings).values({
        id: 1,
        storeName: "SoleVault",
        whatsappNumber: "1234567890",
        currency: "$",
        adminPassword: "admin123",
      });
    }

    // Insert sample products and collect IDs
    const insertedProducts = [];
    for (const product of sampleProducts) {
      const slug = generateSlug(product.name);
      const result = await db.insert(products).values({ ...product, slug }).returning();
      insertedProducts.push(result[0]);
    }

    // Insert reviews mapped to specific products
    let totalReviews = 0;
    for (const [indexStr, reviewList] of Object.entries(productReviewsMap)) {
      const idx = parseInt(indexStr);
      if (idx < insertedProducts.length) {
        const product = insertedProducts[idx];
        for (const review of reviewList) {
          await db.insert(reviews).values({
            productId: product.id,
            ...review,
          });
          totalReviews++;
        }
        // Update product review count and rating
        const avgRating = reviewList.reduce((sum, r) => sum + r.rating, 0) / reviewList.length;
        await db.update(products).set({
          reviewCount: reviewList.length,
          rating: avgRating.toFixed(1),
        }).where(eq(products.id, product.id));
      }
    }

    return NextResponse.json({ success: true, message: `Seeded ${insertedProducts.length} products and ${totalReviews} reviews` });
  } catch (error) {
    console.error("Error seeding:", error);
    return NextResponse.json({ error: "Seeding failed" }, { status: 500 });
  }
}
