import { NextResponse } from "next/server";
import { db } from "@/db";
import { sql } from "drizzle-orm";
import { cookies } from "next/headers";
import { adminSessions } from "@/db/schema";
import { eq } from "drizzle-orm";

async function verifyAdmin(): Promise<boolean> {
  try {
    const cookieStore = await cookies();
    const token = cookieStore.get("admin_session")?.value;
    if (!token) return false;
    const session = await db.select().from(adminSessions).where(eq(adminSessions.token, token));
    if (session.length === 0) return false;
    return new Date(session[0].expiresAt) > new Date();
  } catch { return false; }
}

// Helper - build accented French strings using chr() SQL codes so no encoding layer can corrupt them
// e (acute) = chr(233), e (grave) = chr(232), a (grave) = chr(224), e (circumflex) = chr(234)
// c (cedilla) = chr(231), o (circumflex) = chr(244), i (circumflex) = chr(238), u (circumflex) = chr(251)
// u (grave) = chr(249), o-e = chr(339)

// Each translation is a mapping of review ID to French text using chr() codes
// The frontend will always render the correct UTF-8 characters

interface Translation {
  id: string;
  fr: string; // Raw SQL string using chr() concatenations
}

const translations: Translation[] = [
  { id: "3e75e3f1-9de2-42f9-b50d-7e96475a2147", fr: "Tr' || chr(232) || 's bien." },
  { id: "7d5922f5-aecf-4b55-b7bd-014296680582", fr: "Offertes ' || chr(224) || ' mon p' || chr(232) || 're pour son anniversaire et il ' || chr(233) || 'tait ravi. Le design d''inspiration italienne est ' || chr(233) || 'l' || chr(233) || 'gant et la qualit' || chr(233) || ' du cuir est exceptionnelle. Il les porte non seulement pour conduire mais pour toutes les occasions d' || chr(233) || 'contract' || chr(233) || 'es. J''en ai d' || chr(233) || 'j' || chr(224) || ' command' || chr(233) || ' une paire pour mon mari!" },
  { id: "e4931fd2-86e3-42de-8416-5c84d5310a69", fr: "En tant que passionn' || chr(233) || ' de voitures italiennes, je prends mes chaussures de conduite tr' || chr(232) || 's au s' || chr(233) || 'rieux. Ces mocassins sont exceptionnels - la semelle en caoutchouc martel' || chr(233) || ' donne une sensation parfaite ' || chr(224) || ' la p' || chr(233) || 'dale, et l''int' || chr(233) || 'rieur en cuir non doubl' || chr(233) || ' est incroyablement doux. La couleur tabac d' || chr(233) || 'veloppe une belle patine avec le temps." },
  { id: "3e2d5a84-5ce2-42dd-a888-6c3f5fac8ca1", fr: "Offertes ' || chr(224) || ' mon p' || chr(232) || 're pour son anniversaire et il ' || chr(233) || 'tait ravi. Design italien ' || chr(233) || 'l' || chr(233) || 'gant, qualit' || chr(233) || ' de cuir exceptionnelle. La couleur minuit est ' || chr(233) || 'pur' || chr(233) || 'e et sophistiqu' || chr(233) || 'e. J''ai command' || chr(233) || ' une paire pour mon mari aussi!" },
  { id: "d97fa145-83ce-451d-a304-ad8f8089f990", fr: "Passionn' || chr(233) || ' de voitures italiennes, je suis exigeant sur les chaussures de conduite. Ces mocassins sont exceptionnels. La semelle en caoutchouc offre une sensation parfaite ' || chr(224) || ' la p' || chr(233) || 'dale et l''int' || chr(233) || 'rieur en cuir est incroyablement doux. Un vrai plaisir ' || chr(224) || ' porter au quotidien." },
  { id: "0f646a22-a931-420d-a06c-a8cb97f00935", fr: "Achet' || chr(233) || 'es pour mon copain et il les ADORE. Il dit que ce sont les bottes les plus confortables qu''il ait jamais port' || chr(233) || 'es. Le daim est doux et la semelle en cr' || chr(234) || 'pe offre une excellente flexibilit' || chr(233) || '. Elles ont parfaitement r' || chr(233) || 'sist' || chr(233) || ' ' || chr(224) || ' l''automne et l''hiver - aucun d' || chr(233) || 'g' || chr(226) || 't sous la pluie l' || chr(233) || 'g' || chr(232) || 're. Je recommande vivement!" },
  { id: "ac57a32e-7f03-433b-b666-08ed63b0e7c1", fr: "Les Chukka en Daim ont remplac' || chr(233) || ' toutes mes autres bottes d' || chr(233) || 'contract' || chr(233) || 'es. Le coloris d' || chr(233) || 'sert est magnifique et s''accorde avec absolument tout dans ma garde-robe. La qualit' || chr(233) || ' du daim est incroyable - il a un magnifique grain et une texture qui les fait para' || chr(238) || 'tre bien plus ch' || chr(232) || 'res que 160$. Je les porte au bureau comme en soir' || chr(233) || 'e." },
  { id: "c56e5244-8d90-4337-951a-1604e87b5d1f", fr: "Belles chaussures d' || chr(233) || 'contract' || chr(233) || 'es qui d' || chr(233) || 'passent le rapport qualit' || chr(233) || '-prix. Les coutures sont soign' || chr(233) || 'es, la toile est ' || chr(233) || 'paisse, et elles tiennent bien aux pieds. Mon seul reproche est qu''elles pourraient avoir un peu plus de soutien de la vo' || chr(251) || 'te pour de longues marches. Mais pour un usage quotidien d' || chr(233) || 'contract' || chr(233) || ', elles sont excellentes." },
  { id: "7ee0b7d7-eade-4401-8faa-fb3cf649046e", fr: "La chaussure parfaite pour les week-ends paresseux! Tellement faciles ' || chr(224) || ' enfiler et ' || chr(224) || ' partir. Elles ont l''air bien plus ch' || chr(232) || 'res qu''elles ne le sont - j''ai re' || chr(231) || 'u des compliments de personnes qui pensaient que c''' || chr(233) || 'taient des chaussures de marque. La couleur kaki va avec tout. Mon seul regret est de ne pas les avoir achet' || chr(233) || 'es plus t' || chr(244) || 't." },
  { id: "006abee5-ee2c-4b08-a217-66aae06777ef", fr: "Ces slip-ons sont devenues mes chaussures quotidiennes. Je les enfile pour tout - courses, promenades du chien, d' || chr(238) || 'ners d' || chr(233) || 'contract' || chr(233) || 's, voyages en week-end. La toile est durable et facile ' || chr(224) || ' nettoyer, et la semelle rembourr' || chr(233) || 'e les rend suffisamment confortables pour toute la journ' || chr(233) || 'e. Je les ai maintenant en trois couleurs!" },
  { id: "84a76153-b7e7-4a68-9013-a32520f16bb4", fr: "Sandales super confortables pour le prix. L''amorti est meilleur que certaines sandales qui co' || chr(251) || 'tent trois fois plus. Elles sont parfaites pour faire des courses, promener le chien, ou simplement se d' || chr(233) || 'tendre ' || chr(224) || ' la maison. J''ai enlev' || chr(233) || ' une ' || chr(233) || 'toile car la taille est un peu d' || chr(233) || 'cal' || chr(233) || 'e - je recommande de prendre une pointure au-dessus de votre taille habituelle." },
  { id: "c7f1ae29-9569-447a-a40b-68b093942d09", fr: "Ces sandales sont mes chaussures d''int' || chr(233) || 'rieur maintenant. La semelle en mousse ' || chr(224) || ' m' || chr(233) || 'moire de forme est tellement moelleuse et confortable - je pousse litt' || chr(233) || 'ralement un soupir de soulagement chaque fois que je les enfile apr' || chr(232) || 's une longue journ' || chr(233) || 'e. J''en ai achet' || chr(233) || ' des paires pour toute ma famille tellement elles sont bonnes. La couleur bleu marine est superbe et n''a pas d' || chr(233) || 'color' || chr(233) || ' apr' || chr(232) || 's des mois d''utilisation." },
  { id: "2d8b140a-cf40-459b-bb92-bb057947f13e", fr: "Je les adore pour les journ' || chr(233) || 'es de printemps pluvieuses! Elles gardent mes pieds compl' || chr(232) || 'tement au sec et la semelle a une excellente adh' || chr(233) || 'rence. La couleur rouge est tr' || chr(232) || 's mignonne et re' || chr(231) || 'oit toujours des compliments. J''ai seulement mis 4 ' || chr(233) || 'toiles car elles peuvent devenir un peu chaudes ' || chr(224) || ' des temp' || chr(233) || 'ratures sup' || chr(233) || 'rieures ' || chr(224) || ' 15' || chr(176) || 'C car elles sont enti' || chr(232) || 'rement en caoutchouc. Mais pour leur usage, elles sont parfaites." },
  { id: "38c9526e-b304-4a70-9d02-fea682a18e28", fr: "Les meilleures bottes de pluie qualit' || chr(233) || '-prix du march' || chr(233) || '. J''ai essay' || chr(233) || ' des marques ch' || chr(232) || 'res comme Hunter et Aigle, mais ces Rain Guardian de SoleVault sont tout aussi ' || chr(233) || 'tanches et plus confortables gr' || chr(226) || 'ce ' || chr(224) || ' la doublure en n' || chr(233) || 'opr' || chr(232) || 'ne. En plus, elles co' || chr(251) || 'tent une fraction du prix. La couleur noire est superbe et s''accorde avec tout." },
  { id: "6be37e6d-4aae-4488-9e48-f88e1b601971", fr: "Enfin! Des bottes de pluie qui n''ont pas l''air de bottes de pluie. La couleur vert Hunter est suffisamment ' || chr(233) || 'l' || chr(233) || 'gante pour aller au brunch, mais elles sont enti' || chr(232) || 'rement ' || chr(233) || 'tanches pour piloter dans les flaques sur le chemin du travail. La doublure en n' || chr(233) || 'opr' || chr(232) || 'ne garde mes pieds au chaud et la semelle antid' || chr(233) || 'rapante m''a sauv' || chr(233) || 'e plusieurs fois sur des trottoirs mouill' || chr(233) || 's." },
  { id: "27b20288-5d99-4dfd-b1e2-38bef752c483", fr: "Apr' || chr(232) || 's avoir us' || chr(233) || ' une paire de bottes de travail tous les 6 mois, j''ai investi dans les Lumberjack Pro et elles ont dur' || chr(233) || ' plus d''un an d''usage quotidien intense. La diff' || chr(233) || 'rence de qualit' || chr(233) || ' est imm' || chr(233) || 'diatement visible - le cuir est ' || chr(233) || 'pais et r' || chr(233) || 'silient, la semelle montre ' || chr(224) || ' peine des signes d''usure. La couleur bl' || chr(233) || ' est superbe et cache bien la salet' || chr(233) || '." },
  { id: "bd3a7718-5b0e-4390-96eb-df80a8f844c3", fr: "Je travaille dans la construction et ces bottes sont la vraie affaire. La coque en acier m''a sauv' || chr(233) || ' les pieds au moins deux fois d''outils qui tombaient. Le cuir imperm' || chr(233) || 'able me garde au sec m' || chr(234) || 'me en travaillant sous la pluie, et la semelle anti-fatigue est un game changer pour les journ' || chr(233) || 'es de 12 heures. Ce sont des b' || chr(234) || 'tes de somme qui ont aussi assez d''allure pour un d' || chr(238) || 'ner d' || chr(233) || 'contract' || chr(233) || '." },
  { id: "402bd95a-c850-444a-84f6-d8a748d605d9", fr: "Achet' || chr(233) || 'es pour un voyage en Islande en janvier. J''ai march' || chr(233) || ' sur des glaciers, ' || chr(224) || ' travers des temp' || chr(234) || 'tes de neige, et travers' || chr(233) || ' des rivi' || chr(232) || 'res gel' || chr(233) || 'es. Mes pieds sont rest' || chr(233) || 's au chaud et compl' || chr(232) || 'tement au sec pendant tout le voyage. Elles sont ' || chr(233) || 'galement ' || chr(233) || 'tonnamment confortables pour des bottes lourdes - aucune amp' || chr(244) || 'ule due au rodage. Absolument essentielles pour les aventures en climat froid." },
  { id: "1ded8652-bdc4-47bb-a644-a6714f6f470e", fr: "Je vis au Minnesota o' || chr(249) || ' les hivers atteignent r' || chr(233) || 'guli' || chr(232) || 'rement -34' || chr(176) || 'C. Ces bottes Arctic Commander ont gard' || chr(233) || ' mes pieds au chaud et au sec pendant toute la saison. L''isolation Thinsulate est incroyablement efficace, et le cuir imperm' || chr(233) || 'able a r' || chr(233) || 'sist' || chr(233) || ' au sel, ' || chr(224) || ' la neige fondue et ' || chr(224) || ' la neige profonde. La bande de roulement agressive m''a aussi emp' || chr(234) || 'ch' || chr(233) || ' de glisser sur la glace. Les meilleures bottes d''hiver que j''ai jamais poss' || chr(233) || 'd' || chr(233) || 'es." },
  { id: "9e805af5-aaa6-481c-943d-bbc0d6446072", fr: "Je travaille comme garde forestier et j''ai besoin de bottes fiables tous les jours. Le Trail Blazer X est ma r' || chr(233) || 'f' || chr(233) || 'rence depuis un an. Dans la boue, la neige, la pluie et sur terrain rocheux - ces bottes g' || chr(232) || 'rent tout. Le maintien de la cheville est excellent et emp' || chr(234) || 'che les foulures sur terrain in' || chr(233) || 'gal. D' || chr(233) || 'j' || chr(224) || ' sur ma deuxi' || chr(232) || 'me paire." },
  { id: "44276742-0ef4-44e3-883e-6ee7c5e5c0f3", fr: "Bonnes bottes de randonn' || chr(233) || 'e dans l''ensemble. Tr' || chr(232) || 's robustes et bien construites. L''imperm' || chr(233) || 'abilit' || chr(233) || ' fonctionne parfaitement - je les ai test' || chr(233) || 'es dans des flaques ' || chr(224) || ' la cheville et suis rest' || chr(233) || 'e au sec. La seule raison des 4 ' || chr(233) || 'toiles est qu''elles sont un peu lourdes par rapport aux chaussures de trail, ce qui ralentit sur les longues randonn' || chr(233) || 'es. Mais pour terrain difficile, on veut ce niveau de protection." },
  { id: "d7b853b4-6009-4c99-90f7-a39538e920a3", fr: "Je les ai emmen' || chr(233) || 'es en randonn' || chr(233) || 'e de 5 jours sur le sentier des Appalaches et elles ont ' || chr(233) || 't' || chr(233) || ' absolument ph' || chr(233) || 'nom' || chr(233) || 'nales. L''imperm' || chr(233) || 'abilit' || chr(233) || ' a gard' || chr(233) || ' mes pieds au sec ' || chr(224) || ' travers les travers' || chr(233) || 'es de ruisseaux et la pluie, la bande de roulement adh' || chr(233) || 'rait aux rochers glissants comme de la colle, et le bout renforc' || chr(233) || ' m''a ' || chr(233) || 'vit' || chr(233) || ' des orteils cass' || chr(233) || 's au moins trois fois. ' || chr(201) || 'quipement de randonn' || chr(233) || 'e essentiel." },
  { id: "5d4aa43d-50f0-4920-9fdb-321699bb9e9a", fr: "J''ai pay' || chr(233) || ' 300$ pour celles-ci et elles font para' || chr(238) || 'tre mes Allen Edmonds ' || chr(224) || ' 500$ hors de prix. La couleur cognac est riche et chaleureuse, la forme est ' || chr(233) || 'l' || chr(233) || 'gante sans ' || chr(234) || 'tre trop pointue, et le confort est superbe pour une chaussure habill' || chr(233) || 'e. La semelle Dainite offre une bonne adh' || chr(233) || 'rence sur les surfaces humides. Tout simplement exceptionnel." },
  { id: "24b7b846-26a4-474d-88c8-1dc9fec2cc16", fr: "La construction Goodyear welt sur ces Oxfords est de la vraie qualit' || chr(233) || '. On sent imm' || chr(233) || 'diatement la diff' || chr(233) || 'rence de qualit' || chr(233) || ' par rapport aux chaussures coll' || chr(233) || 'es. Le cuir pleine fleur cr' || chr(233) || 'pite de satisfaction ' || chr(224) || ' l''' || chr(233) || 'tat neuf et d' || chr(233) || 'veloppe du caract' || chr(232) || 're avec le temps. J''ai fait remplacer la semelle une fois et elles ont meilleure allure que jamais. Ce sont des chaussures pour la vie." },
  { id: "5ac6ea3b-3e47-44b9-a93b-3373c8ae04c4", fr: "J''ai achet' || chr(233) || ' la paire marron pour le travail et j''ai ' || chr(233) || 't' || chr(233) || ' tellement impressionn' || chr(233) || ' que je suis revenu pour la noire. La qualit' || chr(233) || ' rivalise avec des chaussures que j''ai vues ' || chr(224) || ' deux fois le prix chez des marques de luxe. Le cuir est doux et souple d' || chr(232) || 's la sortie de la bo' || chr(238) || 'te - pas de p' || chr(233) || 'riode de rodage douloureuse. Ma r' || chr(233) || 'f' || chr(233) || 'rence pour les r' || chr(233) || 'unions clients et ' || chr(233) || 'v' || chr(233) || 'nements formels." },
  { id: "31246b1f-8737-41ae-b764-1c0de71059b6", fr: "Je travaille en finance et j''ai besoin de chaussures qui aient l''air professionnelles jour apr' || chr(232) || 's jour. Ces Leather Elite sont exceptionnelles - l''artisanat est ' || chr(233) || 'vident dans chaque d' || chr(233) || 'tail. Le bord cousu ' || chr(224) || ' la main, la semelle en cuir, la forme parfaitement dessin' || chr(233) || 'e. Apr' || chr(232) || 's 6 mois de port quasi quotidien, elles ont d' || chr(233) || 'velopp' || chr(233) || ' une magnifique patine. Ce sont des chaussures d''investissement." },
  { id: "960c0321-8064-4741-b4e1-3af99ef51052", fr: "Ce sont les plus belles chaussures habill' || chr(233) || 'es que j''aie jamais poss' || chr(233) || 'd' || chr(233) || 'es. Le cuir italien a cette incroyable richesse et profondeur de couleur qu''on ne peut obtenir qu''avec des mat' || chr(233) || 'riaux premium. Je les ai port' || chr(233) || 'es ' || chr(224) || ' un mariage et j''ai re' || chr(231) || 'u plus de compliments sur mes chaussures que la mari' || chr(233) || 'e sur sa robe! Le confort est ' || chr(233) || 'galement remarquable - pas d''amp' || chr(244) || 'ules, pas de serrement." },
  { id: "c5f1ea6e-9484-4310-a27c-0eb64d6629a9", fr: "Je cours depuis 15 ans et celles-ci sont peut-' || chr(234) || 'tre les meilleures chaussures de course que j''aie jamais port' || chr(233) || 'es. L''amorti est parfait - suffisant pour prot' || chr(233) || 'ger lors de longues courses mais assez r' || chr(233) || 'actif pour le travail de vitesse. Je les utilise pour tout, des joggings de r' || chr(233) || 'cup' || chr(233) || 'ration faciles aux sorties tempo et elles excellent partout." },
  { id: "eecf89d8-b91d-4c24-812c-a62810e73268", fr: "La mousse Boost dans celles-ci est de niveau sup' || chr(233) || 'rieur. J''ai couru avec beaucoup de chaussures ' || chr(224) || ' mousse ' || chr(224) || ' retour d''' || chr(233) || 'nergie mais l''HyperBoost Max est dans sa propre cat' || chr(233) || 'gorie. Chaque pas donne l''impression d''un mini trampoline qui vous pousse vers l''avant. J''ai battu mon record du 10K de plus d''une minute lors de ma premi' || chr(232) || 're course avec elles. La couleur noir de base est propre et s''accorde ' || chr(224) || ' tout." },
  { id: "ddd30c12-8539-4184-b353-6b31ee6ef20b", fr: "Excellentes chaussures de longue distance. J''ai termin' || chr(233) || ' trois semi-marathons avec elles et elles ont ' || chr(233) || 't' || chr(233) || ' impeccables. Le maintien de la vo' || chr(251) || 'te est parfait pour mes pieds plats. Mon seul souhait est qu''elles soient disponibles dans plus d''options de couleurs - j''ai d' || chr(251) || ' prendre noir/rouge, ce qui est bien mais je voulais quelque chose de plus unique." },
  { id: "75783353-341e-48c8-8d2e-4d76ddad17dd", fr: "Je suis coach de course et je recommande la Marathon Elite ' || chr(224) || ' tous mes athl' || chr(232) || 'tes qui s''entra' || chr(238) || 'nent pour de longues distances. Le rapport amorti-poids est le meilleur de sa cat' || chr(233) || 'gorie. Elles sont incroyablement l' || chr(233) || 'g' || chr(232) || 'res mais offrent toujours suffisamment de protection pour des courses de plus de 32 km. La couleur jaune fluo est ' || chr(233) || 'galement excellente pour la visibilit' || chr(233) || '." },
  { id: "7914c16c-5ad5-4138-8d47-ffe43d0ff683", fr: "Je me suis entra' || chr(238) || 'n' || chr(233) || ' et j''ai couru mon premier marathon complet avec ces chaussures. 42,2 km et mes pieds se sentaient bien tout le long. La technologie de retour d''' || chr(233) || 'nergie est r' || chr(233) || 'elle - on sent litt' || chr(233) || 'ralement le rebond qui vous propulse vers l''avant dans les derniers kilom' || chr(232) || 'tres quand on est le plus fatigu' || chr(233) || '. Fini en 3h28, je ne pouvais pas ' || chr(234) || 'tre plus heureux!" },
  { id: "6a2a1edd-4bad-439c-80c6-b0abdeebf108", fr: "Je les ai achet' || chr(233) || 'es comme mes premi' || chr(232) || 'res vraies chaussures de course et je suis tellement contente de l''avoir fait. La diff' || chr(233) || 'rence entre celles-ci et mes anciennes baskets est le jour et la nuit. L''amorti absorbe parfaitement l''impact, mes genoux ne me font plus mal apr' || chr(232) || 's les courses, et elles sont assez ' || chr(233) || 'l' || chr(233) || 'gantes pour ' || chr(234) || 'tre port' || chr(233) || 'es au quotidien. Le meilleur investissement que j''ai fait pour ma forme." },
  { id: "814e4c99-749a-44b6-b74f-030da595a202", fr: "Chaussures d''entra' || chr(238) || 'nement quotidien parfaites. Je cours 50-65 km par semaine et elles tiennent magnifiquement. L''adh' || chr(233) || 'rence de la semelle est ph' || chr(233) || 'nom' || chr(233) || 'nale - j''ai couru sous la pluie, sur du gravier, et sur des sentiers sans jamais glisser. Le dessus respirant garde mes pieds au sec et confortables. On ne peut rien demander de plus ' || chr(224) || ' ce prix." },
  { id: "d125626b-4e64-4d70-99a7-a455ea91d525", fr: "Chaussures de performance incroyables. La plaque en carbone vous donne vraiment l''impression d''' || chr(234) || 'tre plus rapide - il y a un ' || chr(233) || 'clat notable ' || chr(224) || ' chaque foul' || chr(233) || 'e. Je donne seulement 4 ' || chr(233) || 'toiles car l''ajustement est tr' || chr(232) || 's ' || chr(233) || 'troit autour du milieu du pied. Si vous avez les pieds larges, prenez une demi-taille au-dessus. Sinon, ce sont des chaussures de course parfaites." },
  { id: "b568ee95-0b91-4d6e-81b2-6038a357c08c", fr: "Ce sont LES chaussures de course ' || chr(224) || ' battre en ce moment. La mousse style ZoomX est incroyablement rebondissante et r' || chr(233) || 'active. J''ai couru plus de 320 km avec elles et elles sont toujours comme neuves. La couleur rouge racing a l''air rapide juste pos' || chr(233) || 'e sur l''' || chr(233) || 'tag' || chr(232) || 're. Si vous ' || chr(234) || 'tes s' || chr(233) || 'rieux au sujet de la course, achetez-les imm' || chr(233) || 'diatement." },
  { id: "96219439-4b79-4dce-816f-929d0bca7507", fr: "En tant que marathonien de comp' || chr(233) || 'tition, je suis tr' || chr(232) || 's exigeant sur mes chaussures de course. La Velocity Pro X m''a bluff' || chr(233) || ' - la plaque en fibre de carbone donne une propulsion incroyable et j''ai battu mon record de 3 minutes lors de ma premi' || chr(232) || 're course avec elles. Le mesh l' || chr(233) || 'ger donne l''impression de ne pas porter de chaussures. Performance d''' || chr(233) || 'lite." },
  { id: "4e86a2ed-1d30-47b3-bf0b-cbb43b3aa048", fr: "J''en suis ' || chr(224) || ' ma troisi' || chr(232) || 'me paire de Cloud Walker car elles sont tellement bonnes. La technologie CloudFoam a quelque chose de sp' || chr(233) || 'cial - elle ' || chr(233) || 'pouse la forme de votre pied avec le temps. Ma premi' || chr(232) || 're paire a dur' || chr(233) || ' 18 mois d''usage quotidien avant que la bande de roulement ne s''use. C''est une durabilit' || chr(233) || ' incroyable pour ce prix." },
  { id: "825130c5-3b28-455f-80ff-58e73f85c499", fr: "Le nom ne ment pas - on a vraiment l''impression de marcher sur des nuages. Je suis facteur et je marche plus de 19 km par jour. Ce sont les seules chaussures qui ne me laissent pas les pieds douloureux ' || chr(224) || ' la fin de la journ' || chr(233) || 'e. La couleur blanche reste facilement propre aussi. J''ach' || chr(232) || 'te une paire de rechange au cas o' || chr(249) || '." },
  { id: "7e09214f-1f33-45c2-bb8e-6948e81b5c07", fr: "J''ai de la fasciite plantaire et trouver des chaussures confortables a ' || chr(233) || 't' || chr(233) || ' un cauchemar pendant des ann' || chr(233) || 'es. Mon podologue a recommand' || chr(233) || ' des chaussures avec un bon soutien de la vo' || chr(251) || 'te, et les Cloud Walker ont d' || chr(233) || 'pass' || chr(233) || ' toutes mes attentes. Je peux rester debout pendant des services de 8 heures au travail sans aucune douleur. Elles ont litt' || chr(233) || 'ralement chang' || chr(233) || ' ma vie. Merci SoleVault!" },
  { id: "36020e0c-309f-4f75-b8aa-8173e158bab3", fr: "Chaussures vraiment amusantes avec un excellent confort. Les accents r' || chr(233) || 'fl' || chr(233) || 'chissants sont un joli d' || chr(233) || 'tail pour les promenades nocturnes. La seule plainte mineure est que la couleur bleu ' || chr(233) || 'lectrique est l' || chr(233) || 'g' || chr(232) || 'rement diff' || chr(233) || 'rente des photos du site - un peu plus violette en personne. Je les aime quand m' || chr(234) || 'me, je souhaite juste que la couleur soit plus fid' || chr(232) || 'le." },
  { id: "450a9aba-94f4-4fd8-878d-b346863ca09b", fr: "OH MON DIEU ces chaussures sont INCROYABLES! Le coloris vert n' || chr(233) || 'on brille litt' || chr(233) || 'ralement sous les lumi' || chr(232) || 'res noires - je les ai port' || chr(233) || 'es en boite de nuit et tout le monde perdait la t' || chr(234) || 'te. Mais elles ne sont pas juste flashy - la semelle en mousse est incroyablement r' || chr(233) || 'active et confortable. J''ai dans' || chr(233) || ' pendant 4 heures sans aucune douleur aux pieds." },
  { id: "8c2b9726-4cf5-48a3-838d-e031a1e3719c", fr: "Les meilleures baskets montantes que j''aie jamais eues. Point. La qualit' || chr(233) || ' de fabrication rappelle les Chuck Taylor classiques mais avec beaucoup plus de confort et de soutien. Je les ai port' || chr(233) || 'es ' || chr(224) || ' des concerts, dans des skateparks et m' || chr(234) || 'me en randonn' || chr(233) || 'e - elles g' || chr(232) || 'rent tout. La couleur verte est unique et est toujours remarqu' || chr(233) || 'e." },
  { id: "2a4ebb3f-fde4-41b7-aeb9-cce0a7cdc3b9", fr: "J''adore le look r' || chr(233) || 'tro montant! Elles se marient parfaitement avec des jeans coup' || chr(233) || 's et une veste en cuir. La semelle rembourr' || chr(233) || 'e est ' || chr(233) || 'tonnamment confortable pour une chaussure en toile. J''ai enlev' || chr(233) || ' une ' || chr(233) || 'toile car les blanches se salissent facilement, mais une gomme magique en vient ' || chr(224) || ' bout. Dans l''ensemble un excellent achat." },
  { id: "0a7b3041-f863-4c72-a480-d2eb25a36b1e", fr: "Les StreetFlex Montantes sont du feu! Je suis un grand fan de sneakers et elles sont imm' || chr(233) || 'diatement devenues ma chaussure num' || chr(233) || 'ro 1. Le soutien de la cheville est l' || chr(233) || 'gitime - je peux faire du skateboard confortablement avec. La qualit' || chr(233) || ' de la toile est ' || chr(233) || 'paisse et durable, pas fine comme certaines autres marques. J''en ai d' || chr(233) || 'j' || chr(224) || ' deux paires." },
  { id: "d677d845-985f-4f94-8796-d530d0c02289", fr: "Ces baskets sont incroyables! Je marche environ 8 km par jour pour le travail et mes pieds me faisaient mal l''apr' || chr(232) || 's-midi. Depuis que je suis pass' || chr(233) || 'e ' || chr(224) || ' l''Air Max Velocity, z' || chr(233) || 'ro douleur. Le maintien de la vo' || chr(251) || 'te est ph' || chr(233) || 'nom' || chr(233) || 'nal. Elles sont aussi super ' || chr(233) || 'l' || chr(233) || 'gantes - des gens m''ont arr' || chr(234) || 't' || chr(233) || 'e dans la rue pour me demander o' || chr(249) || ' je les avais achet' || chr(233) || 'es!" },
  { id: "66390b43-e929-4171-9ccf-00e3706c4c3f", fr: "Baskets vraiment solides. Le niveau de confort est 10/10 d' || chr(232) || 's la sortie de la bo' || chr(238) || 'te - aucune p' || chr(233) || 'riode de rodage n' || chr(233) || 'cessaire. Je donne seulement 4 ' || chr(233) || 'toiles car la taille est l' || chr(233) || 'g' || chr(232) || 'rement grande. Je fais habituellement du 43 mais j''ai d' || chr(251) || ' ' || chr(233) || 'changer pour un 42,5. ' || chr(192) || ' part ' || chr(231) || 'a, elles sont parfaites. Le design est ' || chr(233) || 'pur' || chr(233) || ' et moderne." },
  { id: "d977f314-27ef-47e0-b00b-3faeeeb9a7d2", fr: "Achet' || chr(233) || 'es pour l''anniversaire de mon mari et il ne les a pas quitt' || chr(233) || 'es depuis! La qualit' || chr(233) || ' des mat' || chr(233) || 'riaux est imm' || chr(233) || 'diatement ' || chr(233) || 'vidente quand on les tient. Les coutures sont parfaites, la semelle a une excellente adh' || chr(233) || 'rence, et elles ont l''air encore meilleures en personne que sur les photos. Je pr' || chr(233) || 'vois d' || chr(233) || 'j' || chr(224) || ' d''acheter la paire noire aussi." },
  { id: "aec216fd-6475-40c1-b4bc-eb57652fe4ec", fr: "Je porte des baskets depuis 20 ans et celles-ci sont sans conteste la paire la plus confortable que j''aie jamais eue. L''amorti donne l''impression de marcher sur des nuages, et le dessus en mesh garde mes pieds au frais m' || chr(234) || 'me en ' || chr(233) || 't' || chr(233) || '. Le coloris rouge est absolument magnifique - je re' || chr(231) || 'ois des compliments ' || chr(224) || ' chaque fois que je les porte. ' || chr(199) || 'a vaut chaque centime." },
];

export async function POST() {
  try {
    const isAdmin = await verifyAdmin();
    if (!isAdmin) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    let success = 0;
    let failed = 0;
    const errors: string[] = [];

    for (const t of translations) {
      try {
        // Build raw SQL string with chr() codes embedded
        // Example: UPDATE reviews SET comment_fr = 'Caf' || chr(233) || 'e ...' WHERE id = 'xxx'
        const fullSql = `UPDATE reviews SET comment_fr = '${t.fr}' WHERE id = '${t.id}'`;
        await db.execute(sql.raw(fullSql));
        success++;
      } catch (e) {
        failed++;
        errors.push(`${t.id.slice(0, 8)}: ${e instanceof Error ? e.message : "unknown"}`);
      }
    }

    return NextResponse.json({
      success: true,
      total: translations.length,
      updated: success,
      failed,
      errors: errors.slice(0, 5),
    });
  } catch (error) {
    return NextResponse.json({
      error: "Failed",
      details: error instanceof Error ? error.message : "Unknown"
    }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({
    info: "POST as admin to translate all 49 reviews with proper French accents. Uses chr() codes for bulletproof Unicode.",
    reviewCount: translations.length,
  });
}
